Repository selenide/selenide, pull requests merged in 2018-03, with the labels that each got.

#689 #688 download files with cyrillic names
  CHANGELOG
  src/main/java/com/codeborne/selenide/impl/DownloadFileWithHttpRequest.java
  src/main/java/com/codeborne/selenide/impl/HttpHelper.java
  src/main/java/com/codeborne/selenide/proxy/FileDownloadFilter.java
  src/test/java/com/codeborne/selenide/impl/DownloadFileWithHttpRequestTest.java
  src/test/java/com/codeborne/selenide/impl/HttpHelperTest.java
  src/test/java/com/codeborne/selenide/proxy/FileDownloadFilterTest.java
  src/test/java/integration/FileDownloadViaHttpGetTest.java
  src/test/java/integration/FileDownloadViaProxyTest.java
  src/test/java/integration/LocalHttpServer.java
  src/test/resources/page_with_uploads.html
  src/test/resources/файл-с-русским-названием.txt
Labels: bug, ready

#692 Chromeoptions prefs
  src/main/java/com/codeborne/selenide/Configuration.java
  src/main/java/com/codeborne/selenide/webdriver/ChromeDriverFactory.java
  src/test/java/com/codeborne/selenide/webdriver/ChomeDriverFactoryTest.java
  src/test/java/com/codeborne/selenide/webdriver/ChromeDriverFactoryTest.java
  src/test/java/com/codeborne/selenide/webdriver/SeleniumCapabilitiesHelper.java
Labels: ready

#589 Add TextsInAnyOrder #478
  src/main/java/com/codeborne/selenide/CollectionCondition.java
  src/main/java/com/codeborne/selenide/collections/TextsInAnyOrder.java
  src/test/java/com/codeborne/selenide/collections/TextsInAnyOrderTest.java
Labels: ready

#659 Fix #655"Listeners SoftAsserts: Screenshot: null for FAIL test"
  src/main/java/com/codeborne/selenide/ElementsCollection.java
  src/main/java/com/codeborne/selenide/impl/SelenideElementProxy.java
  src/test/java/integration/errormessages/Helper.java
  src/test/java/integration/testng/SoftAssertTestNGScreenshotsTest.java
Labels: question, ready
