Repository selenide/selenide, pull requests merged in 2018-05, with the labels that each got.

#727 Add cssValue condition.
  src/main/java/com/codeborne/selenide/Condition.java
  src/test/java/com/codeborne/selenide/ConditionTest.java
  src/test/java/integration/SelenideMethodsTest.java
  src/test/resources/page_with_selects_without_jquery.html
Labels: feature

#726 Fix #725 remote browser binary
  CHANGELOG
  src/main/java/com/codeborne/selenide/webdriver/ChromeDriverFactory.java
  src/main/java/com/codeborne/selenide/webdriver/EdgeDriverFactory.java
  src/main/java/com/codeborne/selenide/webdriver/FirefoxDriverFactory.java
  src/main/java/com/codeborne/selenide/webdriver/InternetExplorerDriverFactory.java
  src/main/java/com/codeborne/selenide/webdriver/OperaDriverFactory.java
  src/main/java/com/codeborne/selenide/webdriver/RemoteDriverFactory.java
  src/main/java/com/codeborne/selenide/webdriver/SafariDriverFactory.java
Labels: ready

#731 Add ability to get browser mob proxy instance.
  gradle/dependencies.gradle
  src/main/java/com/codeborne/selenide/proxy/SelenideProxyServer.java
  src/test/java/integration/proxy/ProxyServerUsageTest.java
Labels: feature

#736 Provide webdrivermanager on api level.
  gradle/dependencies.gradle
Labels: feature

#735 Add '?' symbol to filename pattern to avoid url query string parameters.
  src/main/java/com/codeborne/selenide/impl/HttpHelper.java
  src/test/java/com/codeborne/selenide/impl/HttpHelperTest.java
Labels: bug 🐛

#743 Refactor dependencies and introduce sonarqube instead of coveralls
  .travis.yml
  README.md
  build.gradle
  gradle/code-analysis.gradle
  gradle/coverage.gradle
  gradle/dependencies.gradle
  gradle/deploy.gradle
  gradle/tests.gradle
  src/test/java/integration/IntegrationTest.java
Labels: next

#751 Extend isHeadless method with configuration value. Fix #750 issue.
  src/main/java/com/codeborne/selenide/WebDriverRunner.java
Labels: bug 🐛

#744 Refactor dependencies and introduce sonarqube instead of coveralls
  .travis.yml
  README.md
  build.gradle
  gradle/code-analysis.gradle
  gradle/coverage.gradle
  gradle/dependencies.gradle
  gradle/deploy.gradle
  gradle/tests.gradle
  src/test/java/integration/IntegrationTest.java
Labels: feature, ready
