Repository selenide/selenide, pull requests merged in 2020-11, with the labels that each got.

#1303 #1302 show ClickOptions details in report
  src/main/java/com/codeborne/selenide/ClickOptions.java
  src/main/java/com/codeborne/selenide/DownloadOptions.java
  src/main/java/com/codeborne/selenide/files/EmptyFileFilter.java
  src/main/java/com/codeborne/selenide/files/FileFilter.java
  src/test/java/com/codeborne/selenide/ClickOptionsTest.java
  src/test/java/com/codeborne/selenide/DownloadOptionsTest.java
  src/test/java/com/codeborne/selenide/files/EmptyFileFilterTest.java
  src/test/java/com/codeborne/selenide/files/ExtensionFilterTest.java
  src/test/java/com/codeborne/selenide/files/FilenameFilterTest.java
  src/test/java/com/codeborne/selenide/files/FilenameRegexFilterTest.java
Labels: nice to have

#1300 Improve toString for AND condition
  CHANGELOG.md
  src/main/java/com/codeborne/selenide/conditions/And.java
  src/test/java/com/codeborne/selenide/ConditionTest.java
  src/test/java/com/codeborne/selenide/conditions/AndTest.java
Labels: nice to have

#1306 Improve toString for NOT condition
  CHANGELOG.md
  src/main/java/com/codeborne/selenide/conditions/Not.java
  src/test/java/com/codeborne/selenide/conditions/ExplainedConditionTest.java
  src/test/java/com/codeborne/selenide/conditions/NotTest.java
  src/test/java/com/codeborne/selenide/conditions/TextTest.java
Labels: bug 🐛, low priority

#1316 add missing annotations
  src/main/java/com/codeborne/selenide/collections/ExactTextsCaseSensitiveInAnyOrder.java
  src/main/java/com/codeborne/selenide/collections/Texts.java
  src/main/java/com/codeborne/selenide/collections/TextsInAnyOrder.java
  src/main/java/com/codeborne/selenide/ex/AlertNotFoundException.java
  src/main/java/com/codeborne/selenide/ex/DialogTextMismatch.java
  src/main/java/com/codeborne/selenide/ex/ElementIsNotClickableException.java
  src/main/java/com/codeborne/selenide/ex/ElementNotFound.java
  src/main/java/com/codeborne/selenide/ex/ElementShould.java
  src/main/java/com/codeborne/selenide/ex/ElementShouldNot.java
  src/main/java/com/codeborne/selenide/ex/ElementWithTextNotFound.java
  src/main/java/com/codeborne/selenide/ex/ErrorMessages.java
  src/main/java/com/codeborne/selenide/ex/FrameNotFoundException.java
  src/main/java/com/codeborne/selenide/ex/InvalidStateException.java
  src/main/java/com/codeborne/selenide/ex/SoftAssertionError.java
  src/main/java/com/codeborne/selenide/ex/TextsMismatch.java
  src/main/java/com/codeborne/selenide/ex/TextsSizeMismatch.java
  src/main/java/com/codeborne/selenide/ex/TimeoutException.java
  src/main/java/com/codeborne/selenide/ex/UIAssertionError.java
  src/main/java/com/codeborne/selenide/ex/WindowNotFoundException.java
  src/test/java/com/codeborne/selenide/ex/InvalidStateExceptionTest.java
Labels: refactoring

#1308 Fix/1307 multiple download
  CHANGELOG.md
  src/main/java/com/codeborne/selenide/webdriver/ChromeDriverFactory.java
  src/test/java/com/codeborne/selenide/webdriver/ChromeDriverFactoryTest.java
  src/test/resources/downloadMultipleFiles.html
  statics/src/test/java/integration/proxy/MultipleDownloadsTest.java
  statics/src/test/java/integration/proxy/ProxyServerUsageTest.java
Labels: feature

#1312 add parent element to ElementFinder.getSearchCriteria
  src/main/java/com/codeborne/selenide/impl/ElementFinder.java
  src/test/java/com/codeborne/selenide/impl/ElementFinderTest.java
  src/test/java/integration/LastChildTest.java
  src/test/java/integration/SiblingTest.java
  statics/src/test/java/integration/errormessages/ErrorMsgWithScreenshotsTest.java
  statics/src/test/java/integration/errormessages/MethodCalledOnElementFailsOnTest.java
Labels: nice to have

#1319 Setup github actions
  .github/workflows/sast.yml
  .github/workflows/test.yml
  .travis.yml
Labels: refactoring

#1325 upgrade to littleproxy:2.0.1
  gradle/dependencies.gradle
Labels: dependencies
