Repository selenide/selenide, pull requests merged in 2020-07, with the labels that each got.

#1227 #1166 add method `SelenideDriver.screenshot(fileName)`
  CHANGELOG.md
  src/main/java/com/codeborne/selenide/SelenideDriver.java
  statics/src/main/java/com/codeborne/selenide/Screenshots.java
  statics/src/main/java/com/codeborne/selenide/Selenide.java
Labels: feature, nice to have

#1198 Lowercase collections/Texts to texts
  src/main/java/com/codeborne/selenide/collections/Texts.java
  src/test/java/com/codeborne/selenide/CollectionConditionTest.java
  src/test/java/com/codeborne/selenide/collections/TextsTest.java
Labels: waiting-for-contributor

#1194 adding Item With Text collection condition
  src/main/java/com/codeborne/selenide/CollectionCondition.java
  src/main/java/com/codeborne/selenide/collections/ItemWithText.java
  src/main/java/com/codeborne/selenide/ex/ElementWithTextNotFound.java
  src/test/java/com/codeborne/selenide/collections/ItemWithTextTest.java
  src/test/java/com/codeborne/selenide/ex/ElementWithTextNotFoundTest.java
  src/test/java/integration/CollectionMethodsTest.java
Labels: feature, waiting-for-contributor

#1231 #1224 added method `SelenideDriver.screenshot(OutputType)`
  CHANGELOG.md
  config/checkstyle/checkstyle.xml
  src/main/java/com/codeborne/selenide/SelenideDriver.java
  src/main/java/com/codeborne/selenide/impl/ScreenShotLaboratory.java
  statics/src/main/java/com/codeborne/selenide/Selenide.java
  statics/src/test/java/integration/ScreenshotsTest.java
Labels: feature
