Repository selenide/selenide, pull requests merged in 2021-09, with the labels that each got.

#1557 upgrade to JUnit 5.8.0
  gradle/dependencies.gradle
Labels: dependencies

#1565 #1560 un-deprecate method ElementsContainer.getSelf()
  src/main/java/com/codeborne/selenide/ElementsContainer.java
Labels: element-containers

#1579 #1573 - Ability to assert page title
  src/main/java/com/codeborne/selenide/WebDriverConditions.java
  src/main/java/com/codeborne/selenide/conditions/webdriver/Title.java
  statics/src/test/java/integration/WebDriverConditionsTest.java
Labels: feature

#1554 Enhance `closest()` and `ancestor()` methods to search by attribute and attribute w/ value
  src/main/java/com/codeborne/selenide/SelenideElement.java
  src/main/java/com/codeborne/selenide/commands/Ancestor.java
  src/main/java/com/codeborne/selenide/commands/ancestor/AncestorResult.java
  src/main/java/com/codeborne/selenide/commands/ancestor/AncestorRule.java
  src/main/java/com/codeborne/selenide/commands/ancestor/AncestorRuleEngine.java
  src/main/java/com/codeborne/selenide/commands/ancestor/AncestorWithAttributeAndValueRule.java
  src/main/java/com/codeborne/selenide/commands/ancestor/AncestorWithAttributeRule.java
  src/main/java/com/codeborne/selenide/commands/ancestor/AncestorWithClassRule.java
  src/main/java/com/codeborne/selenide/commands/ancestor/AncestorWithTagRule.java
  src/main/java/com/codeborne/selenide/commands/ancestor/SelectorValidation.java
  src/test/java/com/codeborne/selenide/commands/AncestorCommandTest.java
  src/test/java/integration/ParentTest.java
  src/test/resources/page_with_selects_without_jquery.html
Labels: feature

#1583 #984 use gradle format accepted by Dependabot
  build.gradle
Labels: dependencies
