Repository selenide/selenide, pull requests merged in 2021-02, with the labels that each got.

#1408 Ensure that tests formatting numbers work in all machines regarding their user language
  gradle/tests.gradle
  src/test/java/com/codeborne/selenide/impl/DurationFormatTest.java
  src/test/java/com/codeborne/selenide/logevents/SelenideLoggerTest.java
  src/test/java/integration/UseLocaleExtension.java
Labels: refactoring

#1415 added get element alias method
  src/main/java/com/codeborne/selenide/SelenideElement.java
  src/main/java/com/codeborne/selenide/commands/Commands.java
  src/main/java/com/codeborne/selenide/commands/GetAlias.java
  src/main/java/com/codeborne/selenide/impl/WebElementSource.java
  src/main/java/com/codeborne/selenide/impl/WebElementWrapper.java
  src/test/java/com/codeborne/selenide/commands/GetAliasCommandTest.java
Labels: feature

#1418 Make commands customizable
  src/main/java/com/codeborne/selenide/commands/Commands.java
  src/main/java/com/codeborne/selenide/commands/DragAndDropTo.java
  src/main/java/com/codeborne/selenide/impl/Plugins.java
  src/main/resources/META-INF/defaultservices/com.codeborne.selenide.commands.Commands
  src/test/java/integration/OverrideCommandsTest.java
  statics/src/test/java/integration/customcommands/CustomCommandsTest.java
Labels: feature, roadmap
