Repository selenide/selenide, pull requests merged in 2021-11, with the labels that each got.

#1620 Make it easy to configure Selenide Proxy before it's started #1561
  src/main/java/com/codeborne/selenide/drivercommands/CreateDriverCommand.java
  src/main/java/com/codeborne/selenide/proxy/DefaultSelenideProxyServerFactory.java
  src/main/java/com/codeborne/selenide/proxy/SelenideProxyServer.java
  src/main/java/com/codeborne/selenide/proxy/SelenideProxyServerFactory.java
  src/main/resources/META-INF/defaultservices/com.codeborne.selenide.proxy.SelenideProxyServerFactory
  src/test/java/com/codeborne/selenide/proxy/SelenideProxyServerTest.java
  statics/src/test/java/integration/proxy/ProxyServerUsageTest.java
Labels: feature, roadmap

#1634 extract JS code snippets from Java code to separate *.js files
  src/main/java/com/codeborne/selenide/SelenideDriver.java
  src/main/java/com/codeborne/selenide/commands/Click.java
  src/main/java/com/codeborne/selenide/commands/DragAndDropTo.java
  src/main/java/com/codeborne/selenide/commands/GetOwnText.java
  src/main/java/com/codeborne/selenide/commands/SetValue.java
  src/main/java/com/codeborne/selenide/conditions/IsImageLoaded.java
  src/main/java/com/codeborne/selenide/conditions/SelectedText.java
  src/main/java/com/codeborne/selenide/impl/Describe.java
  src/main/java/com/codeborne/selenide/impl/Events.java
  src/main/java/com/codeborne/selenide/impl/JavaScript.java
  src/main/resources/drag_and_drop_script.js
  src/main/resources/get-element-attributes.js
  src/main/resources/get-own-text.js
  src/main/resources/get-selected-text.js
  src/main/resources/is-image.js
  src/main/resources/set-value.js
  src/main/resources/trigger-events.js
  src/main/resources/zoom.js
  src/test/java/com/codeborne/selenide/impl/SelenideElementProxyTest.java
Labels: refactoring

#1628 clean unused code from Click implementation
  src/main/java/com/codeborne/selenide/commands/Click.java
Labels: refactoring

#1601 add selenide.properties support
  src/main/java/com/codeborne/selenide/SelenideConfig.java
  src/main/java/com/codeborne/selenide/impl/PropertiesUtils.java
  statics/src/main/java/com/codeborne/selenide/Configuration.java
Labels: feature

#1637 use MutableCapabilities instead of DesiredCapabilities
  src/main/java/com/codeborne/selenide/SelenideConfig.java
Labels: dependencies

#1638 Up selenium to 4.1.0
  gradle/dependencies.gradle
  src/main/java/com/codeborne/selenide/drivercommands/CreateDriverCommand.java
Labels: dependencies

#1641 #1640 remove method $.shadowRoot()
  src/main/java/com/codeborne/selenide/SelenideElement.java
  src/main/java/com/codeborne/selenide/commands/Commands.java
  src/main/java/com/codeborne/selenide/commands/GetShadowRoot.java
  src/main/java/com/codeborne/selenide/selector/ShadowRoot.java
  src/test/java/integration/ShadowElementTest.java
Labels: dependencies, shadow-dom
