Repository selenide/selenide, pull requests merged in 2021-01, with the labels that each got.

#1363 Override toString for FileFilter classes
  src/main/java/com/codeborne/selenide/DownloadOptions.java
  src/main/java/com/codeborne/selenide/files/EmptyFileFilter.java
  src/main/java/com/codeborne/selenide/files/ExtensionFilter.java
  src/main/java/com/codeborne/selenide/files/FilenameFilter.java
  src/main/java/com/codeborne/selenide/files/FilenameRegexFilter.java
  src/main/java/com/codeborne/selenide/impl/DownloadFileWithHttpRequest.java
  src/test/java/com/codeborne/selenide/files/EmptyFileFilterTest.java
  src/test/java/com/codeborne/selenide/files/ExtensionFilterTest.java
  src/test/java/com/codeborne/selenide/files/FilenameFilterTest.java
  src/test/java/com/codeborne/selenide/files/FilenameRegexFilterTest.java
  statics/src/test/java/integration/FileDownloadViaHttpGetTest.java
Labels: bug 🐛, low priority

#1378 #1376 display duration argument in report as "1s" or "300 ms"
  src/main/java/com/codeborne/selenide/ex/ErrorMessages.java
  src/main/java/com/codeborne/selenide/impl/DurationFormat.java
  src/main/java/com/codeborne/selenide/logevents/SelenideLogger.java
  src/test/java/com/codeborne/selenide/impl/DurationFormatTest.java
  src/test/java/com/codeborne/selenide/logevents/SelenideLoggerTest.java
  statics/src/test/java/integration/proxy/MultipleDownloadsTest.java
Labels: low priority

#1377 Replace long timeout with Duration for ElementsCollection
  src/main/java/com/codeborne/selenide/ElementsCollection.java
  src/test/java/com/codeborne/selenide/ElementsCollectionTest.java
  statics/src/test/java/integration/CollectionWaitTest.java
Labels: refactoring, waiting-for-contributor
