Repository selenide/selenide, pull requests merged in 2022-11, with the labels that each got.

#2006 re-run all integration tests every time
  gradle/tests.gradle
Labels: tests

#2010 Don't change pageLoadTimeout if it is negative. It allows to get rid of spam in error log on appium.
  src/main/java/com/codeborne/selenide/webdriver/WebDriverFactory.java
  statics/src/test/java/integration/PageLoadTimeoutTest.java
Labels: mobile

#2030 #2029 Configuration.browserSize setting is ignored and the size of the browser does not change in headfull chrome
  src/main/java/com/codeborne/selenide/webdriver/AbstractChromiumDriverFactory.java
  src/test/java/com/codeborne/selenide/webdriver/EdgeDriverFactoryTest.java
  statics/src/test/java/integration/ChromiumHeadlessBrowserSizeTest.java
Labels: bug 🐛

#2033 Fix typos in .md files
  .github/ISSUE_TEMPLATE.md
  CONTRIBUTING.md
  README.md
Labels: documentation
