Repository selenide/selenide, pull requests merged in 2022-08, with the labels that each got.

#1902 make HttpClientTimeouts public
  src/main/java/com/codeborne/selenide/webdriver/HttpClientTimeouts.java
Labels: feature

#1894 add cachelookup annotation support
  src/main/java/com/codeborne/selenide/impl/ElementsContainerCollection.java
  src/main/java/com/codeborne/selenide/impl/LazyCollectionSnapshot.java
  src/main/java/com/codeborne/selenide/impl/LazyWebElementSnapshot.java
  src/main/java/com/codeborne/selenide/impl/SelenidePageFactory.java
  src/test/java/com/codeborne/selenide/impl/LazyCollectionSnapshotTest.java
  src/test/java/com/codeborne/selenide/impl/LazyWebElementSnapshotTest.java
  statics/src/test/java/integration/pageobjects/CacheLookupPageObjectTest.java
Labels: feature, brainstorm

#1907 restore IE support in setValue
  src/main/resources/set-value.js
Labels: bug 🐛

#1909 #1891 deprecate TestNG annotation @Report
  modules/testng/src/main/java/com/codeborne/selenide/testng/GlobalTextReport.java
  modules/testng/src/main/java/com/codeborne/selenide/testng/TextReport.java
  modules/testng/src/main/java/com/codeborne/selenide/testng/annotations/Report.java
  modules/testng/src/test/java/com/codeborne/selenide/testng/SoftAssertsTest.java
  modules/testng/src/test/java/com/codeborne/selenide/testng/TextReportTest.java
Labels: feature

#1913 bump Selenium from 4.3.0 to 4.4.0
  gradle/dependencies.gradle
  modules/full-screenshot/src/main/java/com/codeborne/selenide/fullscreenshot/FullSizePhotographer.java
Labels: dependencies

#1919 #1917 fix memory leak
  src/main/java/com/codeborne/selenide/BrowserDownloadsFolder.java
  src/main/java/com/codeborne/selenide/DownloadsFolder.java
  src/main/java/com/codeborne/selenide/SharedDownloadsFolder.java
  src/main/java/com/codeborne/selenide/drivercommands/CloseDriverCommand.java
  src/main/java/com/codeborne/selenide/drivercommands/CreateDriverCommand.java
  src/main/java/com/codeborne/selenide/drivercommands/DisposablesRegistry.java
  src/main/java/com/codeborne/selenide/drivercommands/LazyDriver.java
  src/main/java/com/codeborne/selenide/drivercommands/SelenideDriverFinalCleanupThread.java
  src/main/java/com/codeborne/selenide/drivercommands/WebDriverWrapper.java
  src/main/java/com/codeborne/selenide/drivercommands/WebdriversRegistry.java
  src/main/java/com/codeborne/selenide/impl/Disposable.java
  src/main/java/com/codeborne/selenide/impl/WebDriverInstance.java
  src/test/java/com/codeborne/selenide/drivercommands/DisposablesRegistryTest.java
  src/test/java/com/codeborne/selenide/drivercommands/LazyDriverTest.java
  src/test/java/com/codeborne/selenide/drivercommands/SelenideDriverFinalCleanupThreadTest.java
  statics/src/main/java/com/codeborne/selenide/WebDriverRunner.java
  statics/src/main/java/com/codeborne/selenide/impl/DeadThreadsWatchdog.java
  statics/src/main/java/com/codeborne/selenide/impl/UnusedWebdriversCleanupThread.java
  statics/src/main/java/com/codeborne/selenide/impl/WebDriverContainer.java
  statics/src/main/java/com/codeborne/selenide/impl/WebDriverThreadLocalContainer.java
  statics/src/test/java/com/codeborne/selenide/impl/WebDriverThreadLocalContainerTest.java
Labels: low priority, bug 🐛

#1924 #1923 add condition `partialValue`
  src/main/java/com/codeborne/selenide/Condition.java
  src/main/java/com/codeborne/selenide/conditions/PartialValue.java
  statics/src/test/java/integration/GetSetValueTest.java
Labels: feature

#1929 #1928 add condition $.shouldHave(tagName("div"))
  src/main/java/com/codeborne/selenide/Condition.java
  src/main/java/com/codeborne/selenide/conditions/TagName.java
  src/test/java/com/codeborne/selenide/conditions/TagNameTest.java
  src/test/java/integration/CollectionMethodsTest.java
Labels: feature
