Repository selenide/selenide, pull requests merged in 2022-05, with the labels that each got.

#1798 #1433 remove code that was not needed after introducing SelenideNettyClientFactory
  src/main/java/com/codeborne/selenide/webdriver/HttpClientTimeouts.java
  src/main/java/com/codeborne/selenide/webdriver/SelenideNettyClientFactory.java
  src/main/java/com/codeborne/selenide/webdriver/WebDriverFactory.java
Labels: refactoring

#1809 #1808 Don't move focus to next element when calling $.clear()
  CHANGELOG.md
  build.gradle
  src/main/java/com/codeborne/selenide/commands/Clear.java
  src/test/java/integration/InputFieldTest.java
  src/test/resources/html5_input.html
Labels: bug 🐛

#1811 Add exact own text case-sensitive condition
  src/main/java/com/codeborne/selenide/Condition.java
  src/main/java/com/codeborne/selenide/conditions/ExactOwnTextCaseSensitive.java
  statics/src/test/java/integration/ElementTextTest.java
Labels: feature

#1812 Add own text case-sensitive condition
  src/main/java/com/codeborne/selenide/Condition.java
  src/main/java/com/codeborne/selenide/conditions/OwnTextCaseSensitive.java
  statics/src/test/java/integration/ElementTextTest.java
Labels: feature

#1814 upgrade to webdrivermanager 5.2.0
  modules/core/build.gradle
Labels: dependencies
