Repository selenide/selenide, pull requests merged in 2022-02, with the labels that each got.

#1715 Add selenide's create driver log
  src/main/java/com/codeborne/selenide/drivercommands/CreateDriverCommand.java
  src/test/java/integration/LogEventListenerTest.java
Labels: feature

#1722 Add support for custom duration in `switchTo().frame()`
  CHANGELOG.md
  src/main/java/com/codeborne/selenide/SelenideTargetLocator.java
  src/test/java/integration/FramesCustomWaitTest.java
  src/test/resources/page_with_frames_with_big_delays.html
Labels: feature

#1732 #1731 re-enable using soft assertions in TestNG @Before* and @After* methods
  CHANGELOG.md
  build.gradle
  modules/testng/src/main/java/com/codeborne/selenide/testng/SoftAsserts.java
Labels: soft-asserts

#1737 moving merge of user defined capabilities to match other factories
  CHANGELOG.md
  src/main/java/com/codeborne/selenide/webdriver/FirefoxDriverFactory.java
  src/test/java/com/codeborne/selenide/webdriver/FirefoxDriverFactoryTest.java
Labels: waiting-for-contributor
