Repository selenide/selenide, pull requests merged in 2022-04, with the labels that each got.

#1766 #1765 show both alias and selector in error message
  src/main/java/com/codeborne/selenide/ElementsCollection.java
  src/main/java/com/codeborne/selenide/commands/GetSelectedOptions.java
  src/main/java/com/codeborne/selenide/commands/SelectOptionByTextOrIndex.java
  src/main/java/com/codeborne/selenide/commands/SelectOptionByValue.java
  src/main/java/com/codeborne/selenide/commands/SelectRadio.java
  src/main/java/com/codeborne/selenide/ex/ElementNotFound.java
  src/main/java/com/codeborne/selenide/impl/Alias.java
  src/main/java/com/codeborne/selenide/impl/BySelectorCollection.java
  src/main/java/com/codeborne/selenide/impl/CollectionElement.java
  src/main/java/com/codeborne/selenide/impl/CollectionSnapshot.java
  src/main/java/com/codeborne/selenide/impl/CollectionSource.java
  src/main/java/com/codeborne/selenide/impl/ElementsContainerCollection.java
  src/main/java/com/codeborne/selenide/impl/FilteringCollection.java
  src/main/java/com/codeborne/selenide/impl/HeadOfCollection.java
  src/main/java/com/codeborne/selenide/impl/LastCollectionElement.java
  src/main/java/com/codeborne/selenide/impl/TailOfCollection.java
  src/main/java/com/codeborne/selenide/impl/WebElementSource.java
  src/main/java/com/codeborne/selenide/impl/WebElementsCollectionWrapper.java
  src/test/java/com/codeborne/selenide/ElementsCollectionTest.java
  src/test/java/com/codeborne/selenide/Mocks.java
  src/test/java/com/codeborne/selenide/commands/SelectOptionByTextOrIndexCommandTest.java
  src/test/java/com/codeborne/selenide/commands/SelectRadioCommandTest.java
  src/test/java/com/codeborne/selenide/commands/SelectionOptionByValueCommandTest.java
  src/test/java/com/codeborne/selenide/commands/ToStringCommandTest.java
  src/test/java/com/codeborne/selenide/ex/ElementNotFoundTest.java
  src/test/java/integration/MultipleSelectTest.java
  src/test/java/integration/NamedCollectionsTest.java
  src/test/java/integration/ReportForChainedElementsTest.java
  statics/src/test/java/integration/SelenideMethodsTest.java
  statics/src/test/java/integration/errormessages/WrappedElementTest.java
Labels: feature

#1738 try to use lesser polling interval
  statics/src/test/java/integration/IntegrationTest.java
Labels: tests

#1774 #1773 add non-deprecated `stream()` method to selenide collections
  src/main/java/com/codeborne/selenide/ElementsCollection.java
  src/test/java/integration/CollectionMethodsTest.java
  src/test/java/integration/CollectionWithChangingTextsTest.java
Labels: feature, collections

#1775 chore: Set permissions for GitHub actions
  .github/workflows/sast.yml
Labels: dependencies
