Repository selenide/selenide, pull requests merged in 2022-12, with the labels that each got.

#2044 bump Selenium from 4.6.0 to 4.7.0
  gradle/dependencies.gradle
  src/test/java/integration/SizzleSelectorsTest.java
Labels: dependencies

#2046 #2045 show sessionStorage and localStorage in reports friendly
  src/main/java/com/codeborne/selenide/JSStorage.java
Labels: low priority, bug 🐛

#2051 Selenide#2050: $.select* methods do not fire events
  src/main/resources/select-options-by-index.js
  src/main/resources/select-options-by-partial-text.js
  src/main/resources/select-options-by-text.js
  src/main/resources/select-options-by-value.js
  src/test/resources/select_events.html
  statics/src/test/java/integration/SelectCommandsTest.java
Labels: bug 🐛

#2032 added Press method to accept Key input
  src/main/java/com/codeborne/selenide/SelenideElement.java
  src/main/java/com/codeborne/selenide/commands/Commands.java
  src/main/java/com/codeborne/selenide/commands/Press.java
Labels: feature

#2059 Add syntax highlighting to the example code
  README.md
Labels: documentation

#2075 Automatically merge dependabot's PR if all checks passed
  .github/workflows/test.yml
Labels: dependencies

#2078 Gradle deprecations
  gradle/code-analysis.gradle
  gradle/compilation.gradle
  gradle/coverage.gradle
  gradle/javadoc.gradle
  gradle/publish-module.gradle
  gradle/tests.gradle
Labels: build

#2079 Gradle deprecations
  gradle/publish-module.gradle
  modules/junit4/build.gradle
  modules/testng/build.gradle
Labels: build

#2080 #2050: Improve syntax
  src/main/resources/select-options-by-index.js
  src/main/resources/select-options-by-partial-text.js
  src/main/resources/select-options-by-text.js
  src/main/resources/select-options-by-value.js
Labels: refactoring

#2027 #1817 add methods to copy and paste content
  src/main/java/com/codeborne/selenide/SelenideDriver.java
  src/main/java/com/codeborne/selenide/SelenideElement.java
  src/main/java/com/codeborne/selenide/commands/Commands.java
  src/main/java/com/codeborne/selenide/commands/Paste.java
  statics/src/main/java/com/codeborne/selenide/Selenide.java
Labels: feature

#2084 #2081 create screenshot file with permissions `-rw-r--r--`, not `-rw-------`
  src/main/java/com/codeborne/selenide/impl/ScreenShotLaboratory.java
  src/test/java/com/codeborne/selenide/ModalTest.java
  src/test/java/com/codeborne/selenide/impl/ScreenShotLaboratoryTest.java
Labels: low priority, bug 🐛

#2076 #2038 Fix flaky test in Selenide when downloading file on Windows
  statics/src/test/java/integration/FileDownloadToFolderTest.java
Labels: tests, build

#2089 #2085 fail $.download() if folder still contains "crdownload" files after timeout
  src/main/java/com/codeborne/selenide/impl/DownloadFileToFolder.java
Labels: downloading files

#2093 Split test reports per job
  .github/workflows/test.yml
Labels: build

#2092 fix broken tests on Windows
  src/main/java/com/codeborne/selenide/impl/ScreenShotLaboratory.java
  src/main/java/com/codeborne/selenide/impl/Screenshot.java
  src/test/java/com/codeborne/selenide/impl/ScreenShotLaboratoryTest.java
  src/test/java/com/codeborne/selenide/impl/ScreenshotTest.java
  statics/src/main/java/com/codeborne/selenide/Screenshots.java
Labels: tests
