Repository selenide/selenide, pull requests merged in 2023-03, with the labels that each got.

#2177 use built-in action `gradle-build-action`
  .github/workflows/test.yml
Labels: build

#2179 #2178 improve how "$.getSelectedOption().should*" looks in reports
  src/main/java/com/codeborne/selenide/commands/GetSelectedOption.java
  src/main/java/com/codeborne/selenide/impl/SelenideElementProxy.java
  statics/src/test/java/integration/SelectsTest.java
Labels: reports

#2184 don't write all logs to console when running tests
  .github/workflows/test.yml
  gradle/tests.gradle
  src/test/java/integration/CollectionMethodsTest.java
Labels: tests, build

#2194 #2192 add workaround for Chromedriver 111 issue
  CHANGELOG.md
  build.gradle
  src/main/java/com/codeborne/selenide/webdriver/AbstractChromiumDriverFactory.java
  src/main/resources/versions.properties
  src/test/java/com/codeborne/selenide/webdriver/ChromeDriverFactoryTest.java
  src/test/java/com/codeborne/selenide/webdriver/EdgeDriverFactoryTest.java
Labels: dependencies, workaround

#2208 #2202 fix method $.download(PROXY) after using `using`
  CHANGELOG.md
  build.gradle
  modules/proxy/src/test/java/integration/FileDownloadViaProxyTest.java
  statics/src/main/java/com/codeborne/selenide/Selenide.java
  statics/src/main/java/com/codeborne/selenide/WebDriverRunner.java
  statics/src/main/java/com/codeborne/selenide/impl/WebDriverContainer.java
  statics/src/main/java/com/codeborne/selenide/impl/WebDriverThreadLocalContainer.java
  statics/src/test/java/integration/CustomWebdriverTest.java
Labels: bug 🐛, proxy, downloading files

#2216 #2215 support jdk-http-client instead of NettyClient
  src/main/java/com/codeborne/selenide/webdriver/WebDriverFactory.java
Labels: feature

#2217 fix flaky PageLoadTimeoutTest in Edge browser
  src/test/resources/favicon.ico
Labels: tests

#2189 #2171 [feature] add method $.cached()
  src/main/java/com/codeborne/selenide/SelenideElement.java
  src/main/java/com/codeborne/selenide/commands/CacheSelenideElement.java
  src/main/java/com/codeborne/selenide/commands/Commands.java
  src/main/java/com/codeborne/selenide/commands/SelectRadio.java
  src/main/java/com/codeborne/selenide/impl/ElementsContainerCollection.java
  src/main/java/com/codeborne/selenide/impl/WebElementWrapper.java
  src/test/java/com/codeborne/selenide/impl/WebElementWrapperTest.java
  statics/src/test/java/integration/SelenideMethodsTest.java
Labels: feature

#2091 Added ElementsCollection & CollectionCondition attributes
  src/main/java/com/codeborne/selenide/CollectionCondition.java
  src/main/java/com/codeborne/selenide/ElementsCollection.java
  src/main/java/com/codeborne/selenide/collections/Attributes.java
  src/main/java/com/codeborne/selenide/ex/AttributesMismatch.java
  src/main/java/com/codeborne/selenide/ex/AttributesSizeMismatch.java
  src/test/java/integration/CollectionMethodsTest.java
Labels: feature, collections

#2234 #2227 add method to mock http response with any status
  modules/proxy/src/test/java/integration/proxy/MockResponseWithCorsTest.java
  src/main/java/com/codeborne/selenide/proxy/MockResponseFilter.java
  src/test/resources/page_with_cross-origin-request.html
Labels: feature, proxy
