Repository selenide/selenide, pull requests merged in 2023-04, with the labels that each got.

#2241 Stabilize edge tests
  statics/src/test/java/integration/PageLoadTimeoutTest.java
Labels: tests, build

#2135 #2133 DoubleClick with custom options
  src/main/java/com/codeborne/selenide/SelenideElement.java
  src/main/java/com/codeborne/selenide/commands/Click.java
  src/main/java/com/codeborne/selenide/commands/DoubleClick.java
  src/main/resources/dblclick.js
  src/test/java/integration/DoubleClickTest.java
Labels: feature

#2244 #2135 #2133 fix double-click with offset
  src/main/java/com/codeborne/selenide/SelenideElement.java
  src/main/java/com/codeborne/selenide/commands/Click.java
  src/main/java/com/codeborne/selenide/commands/DoubleClick.java
  src/test/java/integration/Coordinates.java
  src/test/java/integration/DoubleClickTest.java
  src/test/resources/page_with_double_clickable_button.html
  statics/src/test/java/integration/ClickRelativeTest.java
Labels: feature

#2257 bump Selenium from 4.8.3 to 4.9.0
  build.gradle
  gradle/dependencies.gradle
  modules/full-screenshot/src/main/java/com/codeborne/selenide/fullscreenshot/FullSizePhotographer.java
  src/main/resources/versions.properties
Labels: dependencies, java

#2259 #2258 allow setting negative browser position
  src/main/java/com/codeborne/selenide/webdriver/BrowserResizer.java
  src/test/java/com/codeborne/selenide/webdriver/BrowserResizerTest.java
Labels: low priority, bug 🐛

#2267 setBinary is supported by Edge
  src/main/java/com/codeborne/selenide/webdriver/EdgeDriverFactory.java
Labels: feature
