Repository selenide/selenide, pull requests merged in 2023-06, with the labels that each got.

#2319 #2318 use latest version of geckodriver for FF 102+
  src/main/resources/versions.properties
Labels: dependencies

#2328 bump Selenium from 4.9.1 to 4.10.0
  gradle/dependencies.gradle
  modules/full-screenshot/src/main/java/com/codeborne/selenide/fullscreenshot/FullSizePhotographer.java
Labels: dependencies, java

#2331 Fix errors in readme
  modules/appium/README.md
Labels: documentation

#2347 #2346 fix $.doubleClick() in Appium
  modules/appium/src/main/java/com/codeborne/selenide/appium/commands/AppiumDoubleClick.java
  modules/appium/src/main/java/com/codeborne/selenide/appium/commands/SelenideAppiumCommands.java
  modules/appium/src/test/java/it/mobile/android/AndroidClickOptionsTest.java
Labels: low priority, bug 🐛, appium

#2356 #2352 take screenshot even if webdriver has been closed in @AfterEach method
  statics/src/main/java/com/codeborne/selenide/junit5/ScreenShooterExtension.java
Labels: screenshots

#2281 #2268 Add conditions `date(...)` for LocalDate and `datetime(...)` for LocalDateTime to check date values
  src/main/java/com/codeborne/selenide/Condition.java
  src/main/java/com/codeborne/selenide/conditions/datetime/BetweenDateConditionOptions.java
  src/main/java/com/codeborne/selenide/conditions/datetime/BetweenDateTimeConditionOptions.java
  src/main/java/com/codeborne/selenide/conditions/datetime/DateConditionOptions.java
  src/main/java/com/codeborne/selenide/conditions/datetime/DateFormatConditionOptions.java
  src/main/java/com/codeborne/selenide/conditions/datetime/DateTimeConditionOptions.java
  src/main/java/com/codeborne/selenide/conditions/datetime/DateTimeFormatConditionOptions.java
  src/main/java/com/codeborne/selenide/conditions/datetime/EqDateConditionOptions.java
  src/main/java/com/codeborne/selenide/conditions/datetime/EqDateTimeConditionOptions.java
  src/main/java/com/codeborne/selenide/conditions/datetime/LocalDateBetweenCondition.java
  src/main/java/com/codeborne/selenide/conditions/datetime/LocalDateEqualCondition.java
  src/main/java/com/codeborne/selenide/conditions/datetime/LocalDateFormatCondition.java
  src/main/java/com/codeborne/selenide/conditions/datetime/LocalDateTimeBetweenCondition.java
  src/main/java/com/codeborne/selenide/conditions/datetime/LocalDateTimeEqualCondition.java
  src/main/java/com/codeborne/selenide/conditions/datetime/LocalDateTimeFormatCondition.java
  src/main/java/com/codeborne/selenide/conditions/datetime/TemporalFormatCondition.java
  src/test/java/com/codeborne/selenide/conditions/datetime/LocalDateBetweenConditionTest.java
  src/test/java/com/codeborne/selenide/conditions/datetime/LocalDateConditionTest.java
  src/test/java/com/codeborne/selenide/conditions/datetime/LocalDateFormatConditionTest.java
  src/test/java/com/codeborne/selenide/conditions/datetime/LocalDateTimeBetweenConditionTest.java
  src/test/java/com/codeborne/selenide/conditions/datetime/LocalDateTimeConditionTest.java
  src/test/java/com/codeborne/selenide/conditions/datetime/LocalDateTimeFormatConditionTest.java
  src/test/java/integration/DateConditionsTest.java
  src/test/java/integration/DateTimeConditionsTest.java
  src/test/resources/page_with_date_inputs.html
  src/test/resources/page_with_datetime_inputs.html
Labels: feature
