Repository selenide/selenide, pull requests merged in 2023-05, with the labels that each got.

#2272 fix flaky test `FileDownloadToFolderTest.download_byExtension()`
  modules/proxy/src/test/java/integration/FileDownloadViaProxyTest.java
  statics/src/test/java/integration/FileDownloadToFolderTest.java
Labels: tests, downloading files

#2269 #2253 make method $.toString() fast
  src/main/java/com/codeborne/selenide/ElementsCollection.java
  src/main/java/com/codeborne/selenide/SelenideElement.java
  src/main/java/com/codeborne/selenide/collections/PredicateCollectionCondition.java
  src/main/java/com/codeborne/selenide/commands/Commands.java
  src/main/java/com/codeborne/selenide/commands/DescribeElement.java
  src/main/java/com/codeborne/selenide/commands/GetSelectedOptions.java
  src/main/java/com/codeborne/selenide/commands/ToString.java
  src/main/java/com/codeborne/selenide/ex/ListSizeMismatch.java
  src/main/java/com/codeborne/selenide/impl/BySelectorCollection.java
  src/main/java/com/codeborne/selenide/impl/CollectionSnapshot.java
  src/main/java/com/codeborne/selenide/impl/ElementDescriber.java
  src/main/java/com/codeborne/selenide/impl/FilteringCollection.java
  src/main/java/com/codeborne/selenide/impl/HeadOfCollection.java
  src/main/java/com/codeborne/selenide/impl/LazyCollectionSnapshot.java
  src/main/java/com/codeborne/selenide/impl/TailOfCollection.java
  src/main/java/com/codeborne/selenide/impl/WebElementsCollectionWrapper.java
  src/test/java/com/codeborne/selenide/ElementsCollectionTest.java
  src/test/java/com/codeborne/selenide/commands/ToStringCommandTest.java
  src/test/java/com/codeborne/selenide/ex/MatcherErrorTest.java
  src/test/java/com/codeborne/selenide/impl/CollectionElementByConditionTest.java
  src/test/java/com/codeborne/selenide/impl/CollectionElementTest.java
  src/test/java/com/codeborne/selenide/impl/SelenideElementDescriberTest.java
  src/test/java/com/codeborne/selenide/impl/SelenideElementIteratorTest.java
  src/test/java/com/codeborne/selenide/impl/SelenideElementListIteratorTest.java
  src/test/java/integration/CheckboxTest.java
  src/test/java/integration/CollectionMethodsTest.java
  src/test/java/integration/FramesTest.java
  src/test/java/integration/SelenideElementToStringTest.java
  statics/src/test/java/integration/SelenideMethodsTest.java
  statics/src/test/java/integration/errormessages/MethodCalledOnElementPassesOnTest.java
Labels: page objects, performance

#2245 Add method $.dragAndDropTo(WebElement, DragAndDropOptions)
  src/main/java/com/codeborne/selenide/DragAndDropOptions.java
  src/main/java/com/codeborne/selenide/SelenideElement.java
  src/main/java/com/codeborne/selenide/commands/Commands.java
  src/main/java/com/codeborne/selenide/commands/DragAndDropTo.java
  src/test/java/com/codeborne/selenide/DriverStub.java
  src/test/java/com/codeborne/selenide/commands/DragAndDropToTest.java
  statics/src/test/java/integration/JsDragAndDropTest.java
Labels: feature

#2275 remove unused "browser" and "timeout" parameters
  statics/src/test/java/integration/IntegrationTest.java
Labels: refactoring, tests

#2292 Merge selenide selenoid
  .github/workflows/test.yml
  README.md
  gradle/dependencies.gradle
  gradle/tests.gradle
  modules/appium/CHANGELOG
  modules/core/build.gradle
  modules/selenoid/CHANGELOG.md
  modules/selenoid/CONTRIBUTING.md
  modules/selenoid/README.md
  modules/selenoid/build.gradle
  modules/selenoid/src/main/java/org/selenide/selenoid/DownloadFileInSelenoid.java
  modules/selenoid/src/main/java/org/selenide/selenoid/SelenoidClient.java
  modules/selenoid/src/main/java/org/selenide/selenoid/SelenoidClipboard.java
  modules/selenoid/src/main/java/org/selenide/selenoid/SelenoidClipboardService.java
  modules/selenoid/src/main/java/org/selenide/selenoid/SelenoidDownloadsFolder.java
  modules/selenoid/src/main/java/org/selenide/selenoid/StringListType.java
  modules/selenoid/src/main/resources/META-INF/services/com.codeborne.selenide.ClipboardService
  modules/selenoid/src/main/resources/META-INF/services/com.codeborne.selenide.impl.DownloadFileToFolder
  modules/selenoid/src/test/java/it/selenoid/FileDownloadTest.java
  modules/selenoid/src/test/java/it/selenoid/RemoteWebdriverTest.java
  modules/selenoid/src/test/java/it/selenoid/SelenoidClipboardTest.java
  modules/selenoid/src/test/java/it/selenoid/SelenoidSetup.java
  modules/selenoid/src/test/java/org/selenide/selenoid/SelenoidClientTest.java
  modules/selenoid/src/test/resources/simplelogger.properties
  settings.gradle
  statics/src/main/java/com/codeborne/selenide/Selenide.java
Labels: refactoring, build

#2290 #2288 Wait until element becomes enabled before click
  src/main/java/com/codeborne/selenide/SelenideElement.java
  src/main/java/com/codeborne/selenide/commands/Click.java
  src/main/java/com/codeborne/selenide/impl/WebElementSource.java
  src/test/resources/page_with_disabled_button_click.html
  statics/src/test/java/integration/ClickDisabledButtonTest.java
  statics/src/test/java/integration/errormessages/MethodCalledOnElementFailsOnTest.java
  statics/src/test/java/integration/errormessages/MissingElementTest.java
Labels: feature

#2284 #2283 Escape special characters in subject
  src/main/java/com/codeborne/selenide/logevents/SimpleReport.java
  src/test/java/com/codeborne/selenide/logevents/SimpleReportTest.java
  src/test/resources/simple-report-test6.txt
Labels: reports

#2308 Refactor API for switching context in mobile app
  modules/appium/src/main/java/com/codeborne/selenide/appium/SelenideAppium.java
  modules/appium/src/main/java/com/codeborne/selenide/appium/SelenideAppiumTargetLocator.java
  modules/appium/src/test/java/it/mobile/android/ContextTest.java
Labels: refactoring, appium

#2315 #2311 fix appium combined locator in reports
  modules/appium/src/main/java/com/codeborne/selenide/appium/selector/ByTagAndAttribute.java
  modules/appium/src/main/java/com/codeborne/selenide/appium/selector/CombinedBy.java
  modules/appium/src/main/java/com/codeborne/selenide/appium/selector/WithTagAndAttribute.java
  modules/appium/src/test/java/com/codeborne/selenide/appium/AppiumSelectorsTest.java
  modules/appium/src/test/java/com/codeborne/selenide/appium/selector/ByTagAndAttributeTest.java
  modules/appium/src/test/java/com/codeborne/selenide/appium/selector/ByTagAndTextTest.java
  modules/appium/src/test/java/com/codeborne/selenide/appium/selector/ByTextTest.java
  modules/appium/src/test/java/com/codeborne/selenide/appium/selector/WithTagAndAttributeTest.java
  modules/appium/src/test/java/com/codeborne/selenide/appium/selector/WithTagAndTextTest.java
  modules/appium/src/test/java/com/codeborne/selenide/appium/selector/WithTextTest.java
  modules/appium/src/test/java/it/mobile/android/AndroidSelectorsTest.java
  modules/appium/src/test/java/it/mobile/ios/IosSelectorsTest.java
Labels: bug 🐛, reports, appium
