Repository selenide/selenide, pull requests merged in 2023-01, with the labels that each got.

#2103 made setvalueoptions contructor as protected to reuse in selenide-appium
  src/main/java/com/codeborne/selenide/SetValueOptions.java
Labels: feature, mobile

#2106 fix PR: make methods static & add braces to JS code
  src/main/java/com/codeborne/selenide/SelenideDriver.java
  statics/src/main/java/com/codeborne/selenide/Selenide.java
Labels: bug 🐛

#2108 Copy/Paste tests for PR #2027
  statics/src/test/java/integration/CopyPasteTest.java
  statics/src/test/java/integration/DefaultClipboardTest.java
  statics/src/test/java/integration/IntegrationTest.java
Labels: tests

#2114 #2108 fix failing tests introduced in PR #2108
  src/test/resources/start_page.html
  statics/src/test/java/integration/CopyPasteTest.java
Labels: tests

#2119 support the case when file modification time is 0
  src/main/java/com/codeborne/selenide/impl/DownloadFileToFolder.java
  src/test/java/com/codeborne/selenide/impl/DownloadFileToFolderTest.java
  statics/src/test/java/integration/FileDownloadToFolderTest.java
Labels: low priority, bug 🐛, downloading files

#2131 truncate only WebDriverException message
  src/main/java/com/codeborne/selenide/impl/Cleanup.java
  src/test/java/com/codeborne/selenide/impl/CleanupTest.java
Labels: low priority, bug 🐛

#2132 remove step "git checkout HEAD^2" from github actions
  .github/workflows/sast.yml
Labels: build

#2136 bump Selenide from 4.7.2 to 4.8.0
  gradle/dependencies.gradle
Labels: dependencies

#2137 once again, truncate only messages of WebDriverException :)
  src/main/java/com/codeborne/selenide/ex/UIAssertionError.java
  src/main/java/com/codeborne/selenide/impl/Cleanup.java
Labels: low priority, bug 🐛
