Repository selenide/selenide, pull requests merged in 2024-12, with the labels that each got.

#2915 #2914 add debug logs for adding/removing listeners
  src/main/java/com/codeborne/selenide/logevents/SelenideLogger.java
Labels: documentation, reports

#2809 #2769 add method `$.scroll()` with direction and length parameters
  src/main/java/com/codeborne/selenide/ScrollDirection.java
  src/main/java/com/codeborne/selenide/ScrollOptions.java
  src/main/java/com/codeborne/selenide/SelenideElement.java
  src/main/java/com/codeborne/selenide/commands/Commands.java
  src/main/java/com/codeborne/selenide/commands/Scroll.java
  src/test/java/integration/ScrollTest.java
  src/test/resources/page_with_scroll_element.html
Labels: feature

#2925 #2769 #2809 re-run flaky test ScrollTest
  src/test/resources/page_with_scroll_element.html
Labels: tests
