Repository selenide/selenide, pull requests merged in 2024-09, with the labels that each got.

#2837 bump LittleProxy from 2.2.4 to 2.3.0
  gradle/dependencies.gradle
Labels: dependencies, proxy

#2840 #2836 don't try to close any windows when downloading a file
  src/main/java/com/codeborne/selenide/impl/DownloadFileToFolder.java
  src/main/java/com/codeborne/selenide/impl/DownloadFileWithProxyServer.java
  src/main/java/com/codeborne/selenide/impl/WindowsCloser.java
  src/test/java/com/codeborne/selenide/impl/DownloadFileToFolderTest.java
  src/test/java/com/codeborne/selenide/impl/DownloadFileWithProxyServerTest.java
  src/test/java/com/codeborne/selenide/impl/DummyWindowsCloser.java
  src/test/java/com/codeborne/selenide/impl/WindowsCloserTest.java
Labels: downloading files

#2839 #2830 generate error details only once during error construction
  modules/grid/src/main/java/org/selenide/grid/GridDownloader.java
  src/main/java/com/codeborne/selenide/BaseElementsCollection.java
  src/main/java/com/codeborne/selenide/Modal.java
  src/main/java/com/codeborne/selenide/SelenideTargetLocator.java
  src/main/java/com/codeborne/selenide/WebElementsCondition.java
  src/main/java/com/codeborne/selenide/collections/Attributes.java
  src/main/java/com/codeborne/selenide/commands/SelectOptionByTextOrIndex.java
  src/main/java/com/codeborne/selenide/commands/SelectOptionByValue.java
  src/main/java/com/codeborne/selenide/commands/SelectOptionContainingText.java
  src/main/java/com/codeborne/selenide/commands/SelectRadio.java
  src/main/java/com/codeborne/selenide/commands/SetSelected.java
  src/main/java/com/codeborne/selenide/commands/SetValue.java
  src/main/java/com/codeborne/selenide/ex/AlertNotFoundError.java
  src/main/java/com/codeborne/selenide/ex/AttributesMismatch.java
  src/main/java/com/codeborne/selenide/ex/ConditionMetError.java
  src/main/java/com/codeborne/selenide/ex/ConditionNotMetError.java
  src/main/java/com/codeborne/selenide/ex/DialogTextMismatch.java
  src/main/java/com/codeborne/selenide/ex/DoesNotContainTextsError.java
  src/main/java/com/codeborne/selenide/ex/ElementIsNotClickableError.java
  src/main/java/com/codeborne/selenide/ex/ElementNotFound.java
  src/main/java/com/codeborne/selenide/ex/ElementShould.java
  src/main/java/com/codeborne/selenide/ex/ElementShouldNot.java
  src/main/java/com/codeborne/selenide/ex/ElementWithTextNotFound.java
  src/main/java/com/codeborne/selenide/ex/ErrorFormatter.java
  src/main/java/com/codeborne/selenide/ex/FileNotDownloadedError.java
  src/main/java/com/codeborne/selenide/ex/FrameNotFoundError.java
  src/main/java/com/codeborne/selenide/ex/InvalidStateError.java
  src/main/java/com/codeborne/selenide/ex/ListSizeMismatch.java
  src/main/java/com/codeborne/selenide/ex/MatcherError.java
  src/main/java/com/codeborne/selenide/ex/ObjectConditionError.java
  src/main/java/com/codeborne/selenide/ex/SelenideErrorFormatter.java
  src/main/java/com/codeborne/selenide/ex/TextsMismatch.java
  src/main/java/com/codeborne/selenide/ex/UIAssertionError.java
  src/main/java/com/codeborne/selenide/ex/WindowNotFoundError.java
  src/main/java/com/codeborne/selenide/impl/CollectionElement.java
  src/main/java/com/codeborne/selenide/impl/DownloadFileToFolder.java
  src/main/java/com/codeborne/selenide/impl/DownloadFileWithCdp.java
  src/main/java/com/codeborne/selenide/impl/DownloadFileWithHttpRequest.java
  src/main/java/com/codeborne/selenide/impl/DownloadFileWithProxyServer.java
  src/main/java/com/codeborne/selenide/impl/Downloads.java
  src/main/java/com/codeborne/selenide/impl/ElementsContainerCollection.java
  src/main/java/com/codeborne/selenide/impl/ExceptionWrapper.java
  src/main/java/com/codeborne/selenide/impl/LastCollectionElement.java
  src/main/java/com/codeborne/selenide/impl/Waiter.java
  src/main/java/com/codeborne/selenide/impl/WebElementSource.java
  src/test/java/com/codeborne/selenide/ex/DialogTextMismatchTest.java
  src/test/java/com/codeborne/selenide/ex/ElementIsNotClickableErrorTest.java
  src/test/java/com/codeborne/selenide/ex/ElementNotFoundTest.java
  src/test/java/com/codeborne/selenide/ex/ElementShouldNotTest.java
  src/test/java/com/codeborne/selenide/ex/ElementShouldTest.java
  src/test/java/com/codeborne/selenide/ex/ElementWithTextNotFoundTest.java
  src/test/java/com/codeborne/selenide/ex/InvalidStateErrorTest.java
  src/test/java/com/codeborne/selenide/ex/ListSizeMismatchTest.java
  src/test/java/com/codeborne/selenide/ex/MatcherErrorTest.java
  src/test/java/com/codeborne/selenide/ex/TextsMismatchTest.java
  src/test/java/com/codeborne/selenide/ex/UIAssertionErrorTest.java
  src/test/java/com/codeborne/selenide/impl/CollectionElementByConditionTest.java
  src/test/java/com/codeborne/selenide/impl/CollectionElementTest.java
  src/test/java/com/codeborne/selenide/impl/SelenideElementProxyTest.java
Labels: bug 🐛, refactoring

#2841 Add few builder methods for DownloadOptions
  modules/grid/src/test/java/integration/DownloadFileFromGridToFolderTest.java
  modules/grid/src/test/java/integration/DownloadFileFromGridWithCdpTest.java
  modules/proxy/src/test/java/integration/FileDownloadViaProxyTest.java
  modules/proxy/src/test/java/integration/proxy/MultipleDownloadsTest.java
  modules/selenoid/src/test/java/it/selenoid/FileDownloadTest.java
  src/main/java/com/codeborne/selenide/DownloadOptions.java
  src/main/java/com/codeborne/selenide/SelenideElement.java
  src/main/java/com/codeborne/selenide/commands/DownloadFile.java
  src/main/java/com/codeborne/selenide/impl/Arguments.java
  src/test/java/com/codeborne/selenide/DownloadOptionsTest.java
  src/test/java/com/codeborne/selenide/impl/ArgumentsTest.java
  statics/src/test/java/integration/CustomOneTimeWebdriverTest.java
  statics/src/test/java/integration/CustomWebdriverTest.java
  statics/src/test/java/integration/FileDownloadToFolderTest.java
  statics/src/test/java/integration/FileDownloadToFolderWithCdpTest.java
  statics/src/test/java/integration/FileDownloadViaHttpGetTest.java
Labels: downloading files

#2844 #2172 Add sample usage for "step" method
  src/main/java/com/codeborne/selenide/logevents/SelenideLog.java
  src/main/java/com/codeborne/selenide/logevents/SimpleReport.java
  src/test/java/com/codeborne/selenide/logevents/SimpleReportTest.java
  src/test/resources/page_with_date_input.html
  statics/src/test/java/integration/StepsTest.java
Labels: tests

#2851 bump Selenium from 4.24.0 to 4.25.0
  .github/workflows/test-with-selenium-nightly-build.yml
  CHANGELOG.md
  build.gradle
  gradle/dependencies.gradle
  modules/full-screenshot/src/main/java/com/codeborne/selenide/fullscreenshot/FullSizePhotographer.java
  src/main/java/com/codeborne/selenide/DefaultClipboard.java
  src/main/java/com/codeborne/selenide/impl/DownloadFileWithCdp.java
  src/test/java/integration/ITest.java
Labels: dependencies

#2826 Fix deprecated github actions
  .github/workflows/test.yml
Labels: build

#2852 add method Configuration.config()
  statics/src/main/java/com/codeborne/selenide/Configuration.java
  statics/src/test/java/com/codeborne/selenide/ConfigurationTest.java
  statics/src/test/java/integration/LazyEvaluationTest.java
Labels: feature

#2863 Periodically upload test apps to Browserstack
  .github/upload_test_apps.sh
  .github/workflows/upload-app-browserstack.yml
  modules/appium/src/test/java/it/mobile/android/driverproviders/ci/AndroidDriverWithDemos.java
  modules/appium/src/test/java/it/mobile/android/driverproviders/ci/AndroidDriverWithSwagLabs.java
  modules/appium/src/test/java/it/mobile/ios/driverproviders/IosDriverProvider.java
Labels: build, appium
