Repository selenide/selenide, pull requests merged in 2024-02, with the labels that each got.

#2567 #2550 Implement downloading files via CDP
  src/main/java/com/codeborne/selenide/FileDownloadMode.java
  src/main/java/com/codeborne/selenide/commands/DownloadFile.java
  src/main/java/com/codeborne/selenide/impl/DownloadFileToFolder.java
  src/main/java/com/codeborne/selenide/impl/DownloadFileToFolderCdp.java
  src/main/resources/META-INF/defaultservices/com.codeborne.selenide.impl.DownloadFileToFolderCdp
  src/test/java/com/codeborne/selenide/commands/DownloadFileTest.java
  statics/src/test/java/integration/FileDownloadToFolderWithCdpTest.java
Labels: feature, roadmap, downloading files

#2640 #2590 Add method `$.is(visible, timeout)`
  src/main/java/com/codeborne/selenide/SelenideElement.java
  src/main/java/com/codeborne/selenide/commands/Matches.java
  statics/src/test/java/integration/IfWithTimeoutTest.java
Labels: feature

#2556 Add Animated Condition
  src/main/java/com/codeborne/selenide/Condition.java
  src/main/java/com/codeborne/selenide/conditions/Animated.java
  src/main/resources/animation.js
  src/test/java/integration/AnimationTest.java
  src/test/resources/animations.html
Labels: feature

#2652 fix "toString()" method for page object fields
  src/main/java/com/codeborne/selenide/SelenideWait.java
  src/main/java/com/codeborne/selenide/impl/ElementsContainerCollection.java
  src/main/java/com/codeborne/selenide/impl/SelenideElementDescriber.java
  src/test/java/com/codeborne/selenide/impl/BySelectorCollectionTest.java
  src/test/java/com/codeborne/selenide/impl/ElementFinderTest.java
  src/test/java/com/codeborne/selenide/impl/SelenideElementDescriberTest.java
  statics/src/test/java/integration/RadioTest.java
  statics/src/test/java/integration/errormessages/MissingElementTest.java
  statics/src/test/java/integration/pageobjects/FieldOfGenericTypeTest.java
  statics/src/test/java/integration/pageobjects/LazyPageObjectTest.java
  statics/src/test/java/integration/pageobjects/PageObjectWithAliasesTest.java
Labels: refactoring, page objects

#2655 bump Selenium from 4.17.0 to 4.18.0
  .github/workflows/test-with-selenium-nightly-build.yml
  CHANGELOG.md
  gradle/dependencies.gradle
Labels: dependencies

#2660 #1687 #2659 simplify code for retrieving downloaded files from Grid
  modules/grid/build.gradle
  modules/grid/src/main/java/org/selenide/grid/DownloadFileInGrid.java
  modules/grid/src/main/java/org/selenide/grid/GridClient.java
  modules/grid/src/main/java/org/selenide/grid/GridDownloadsFolder.java
  modules/grid/src/test/java/integration/AbstractGridTest.java
  modules/grid/src/test/java/integration/SeleniumGridTest.java
  modules/grid/src/test/java/org/selenide/grid/GridClientTest.java
  src/main/java/com/codeborne/selenide/impl/WebdriverUnwrapper.java
Labels: refactoring, downloading files

#2661 #2550 #1687 Download files via CDP in Selenium Grid and Selenoid
  modules/grid/src/main/java/org/selenide/grid/DownloadFileFromGridToFolder.java
  modules/grid/src/main/java/org/selenide/grid/DownloadFileFromGridWithCdp.java
  modules/grid/src/main/java/org/selenide/grid/GridDownloader.java
  modules/grid/src/main/java/org/selenide/grid/GridDownloadsFolder.java
  modules/grid/src/main/resources/META-INF/services/com.codeborne.selenide.impl.DownloadFileToFolder
  modules/grid/src/main/resources/META-INF/services/com.codeborne.selenide.impl.DownloadFileWithCdp
  modules/grid/src/test/java/integration/AbstractGridTest.java
  modules/grid/src/test/java/integration/DownloadFileFromGridToFolderTest.java
  modules/grid/src/test/java/integration/DownloadFileFromGridWithCdpTest.java
  modules/selenoid/build.gradle
  modules/selenoid/src/main/java/org/selenide/selenoid/DownloadFileFromSelenoidToFolder.java
  modules/selenoid/src/main/java/org/selenide/selenoid/DownloadFileFromSelenoidWithCdp.java
  modules/selenoid/src/main/java/org/selenide/selenoid/SelenoidClient.java
  modules/selenoid/src/main/java/org/selenide/selenoid/SelenoidClipboard.java
  modules/selenoid/src/main/java/org/selenide/selenoid/SelenoidDownloader.java
  modules/selenoid/src/main/java/org/selenide/selenoid/SelenoidDownloadsFolder.java
  modules/selenoid/src/main/resources/META-INF/services/com.codeborne.selenide.impl.DownloadFileToFolder
  modules/selenoid/src/main/resources/META-INF/services/com.codeborne.selenide.impl.DownloadFileWithCdp
  modules/selenoid/src/test/java/it/selenoid/FileDownloadTest.java
  src/main/java/com/codeborne/selenide/BrowserDownloadsFolder.java
  src/main/java/com/codeborne/selenide/DownloadsFolder.java
  src/main/java/com/codeborne/selenide/Driver.java
  src/main/java/com/codeborne/selenide/commands/DownloadFile.java
  src/main/java/com/codeborne/selenide/impl/DownloadFileWithCdp.java
  src/main/resources/META-INF/defaultservices/com.codeborne.selenide.impl.DownloadFileToFolderCdp
  src/main/resources/META-INF/defaultservices/com.codeborne.selenide.impl.DownloadFileWithCdp
  src/test/java/com/codeborne/selenide/commands/DownloadFileTest.java
Labels: feature, downloading files, selenoid
