Repository selenide/selenide, pull requests merged in 2024-05, with the labels that each got.

#2744 * bump Selenium from 4.20.0 to 4.21.0
  .github/workflows/test-with-selenium-nightly-build.yml
  gradle/dependencies.gradle
  modules/full-screenshot/src/main/java/com/codeborne/selenide/fullscreenshot/FullSizePhotographer.java
  src/main/java/com/codeborne/selenide/impl/DownloadFileWithCdp.java
Labels: dependencies

#2745 [refactoring] instead of catching all Errors, catch only AssertionErrors
  src/main/java/com/codeborne/selenide/BaseElementsCollection.java
Labels: refactoring

#2753 Bump checkstyle from 9.3 to 10.17.0
  gradle/code-analysis.gradle
Labels: dependencies, build
