Repository selenide/selenide, pull requests merged in 2025-10, with the labels that each got.

#3131 Add missing `List<Screenshot> screenshots()` to `ScreenShotLaboratory`
  src/main/java/com/codeborne/selenide/impl/ScreenShotLaboratory.java
Labels: screenshots

#3128 Avoid duplicate code
  src/main/java/com/codeborne/selenide/impl/ScreenShotLaboratory.java
Labels: refactoring

#3133 update Selenium from 4.35.0 to 4.36.0
  .github/workflows/test-with-selenium-nightly-build.yml
  gradle/dependencies.gradle
  modules/full-screenshot/src/main/java/com/codeborne/selenide/fullscreenshot/FullSizePhotographer.java
  modules/video-recorder/src/main/java/org/selenide/videorecorder/core/ScreenShooter.java
  src/main/java/com/codeborne/selenide/DefaultClipboard.java
  src/main/java/com/codeborne/selenide/impl/DownloadFileWithCdp.java
  src/test/java/integration/ITest.java
Labels: dependencies

#3134 Allow to pass custom `ScreenShotLaboratory` to `SelenideDriver`
  src/main/java/com/codeborne/selenide/SelenideDriver.java
Labels: refactoring, screenshots
